version: '3'

services:
  nginx-service:
    image: nginx
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/marketplace
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php81-service:
    image: php:8-fpm-alpine
    container_name: php81-container
    hostname: php81-service
    volumes:
      - ./:/var/www/marketplace
    ports:
      - "9000:9000"
  ###> doctrine/doctrine-bundle ###
  database-service:
    container_name: database-container
    image: "postgres:${POSTGRES_VERSION:-15}-alpine"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-marketplace}"
      # You should definitely change the password in production
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-12345}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
